[package]
name = "portfolio-website"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = { version = "1.0", features = ["full"] }
serde = "1.0.228"
tera = "1.20.1"
tower-http = { version = "0.6.8", features = ["fs"] } 
